import type { SupabaseClient } from "@supabase/supabase-js";
import { isSmtpConfigured, sendMail } from "@/lib/email";
import { notifyOwner } from "@/lib/whatsapp";

function row(label: string, value: string | null | undefined) {
  return `<tr>
    <td style="padding:6px 10px;border:1px solid #ddd;background:#f8fafc;font-weight:600;white-space:nowrap">${label}</td>
    <td style="padding:6px 10px;border:1px solid #ddd">${value ?? "—"}</td>
  </tr>`;
}

function links(label: string, urls: (string | null)[]) {
  const valid = urls.filter(Boolean) as string[];
  if (!valid.length) return row(label, "—");
  const html = valid
    .map((u, i) => `<a href="${u}">file ${i + 1}</a>`)
    .join(" &nbsp; ");
  return row(label, html);
}

/** Build + email the Yale completion report for a finished job, and notify the owner. */
export async function sendCompletionReport(
  supabase: SupabaseClient,
  jobId: string
): Promise<void> {
  const { data: job } = await supabase
    .from("jobs")
    .select(
      "id, serial_number, completed_at, reached_lat, reached_lng, completed_lat, completed_lng, technician:technicians(name, phone), lead:leads(*)"
    )
    .eq("id", jobId)
    .single();
  if (!job) return;

  const j = job as unknown as {
    serial_number: string | null;
    completed_at: string | null;
    completed_lat: number | null;
    completed_lng: number | null;
    technician: { name?: string } | null;
    lead: Record<string, unknown>;
  };
  const lead = j.lead;
  const tech = j.technician;

  const { data: jobDocs } = await supabase
    .from("job_docs")
    .select("completion_photo_urls, bill_url, serial_image_url")
    .eq("job_id", jobId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  const { data: custDocs } = await supabase
    .from("customer_docs")
    .select("invoice_url, preferred_date, preferred_time, media_urls")
    .eq("lead_id", lead.id as string)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  const mapsLink =
    j.completed_lat && j.completed_lng
      ? `https://maps.google.com/?q=${j.completed_lat},${j.completed_lng}`
      : null;

  const html = `
  <div style="font-family:Arial,sans-serif;color:#0f172a">
    <h2>Yale Service Completion Report</h2>
    <table style="border-collapse:collapse;font-size:14px">
      ${row("Brand Ticket ID", lead.yale_ref_no as string)}
      ${row("Call Type", lead.request_type as string)}
      ${row("Customer Name", lead.customer_name as string)}
      ${row("Customer Mobile", lead.phone as string)}
      ${row("Address", lead.address as string)}
      ${row("Model", lead.model as string)}
      ${row("Serial No (OCR)", j.serial_number)}
      ${row("Technician", tech?.name)}
      ${row("Job Close Date", j.completed_at ? new Date(j.completed_at).toLocaleString("en-IN") : null)}
      ${row("Ticket Status", "CLOSED")}
      ${row("Completion GPS", mapsLink ? `<a href="${mapsLink}">${j.completed_lat}, ${j.completed_lng}</a>` : null)}
      ${links("Completion Photos", jobDocs?.completion_photo_urls ?? [])}
      ${links("Bill", [jobDocs?.bill_url ?? null])}
      ${links("Serial Image", [jobDocs?.serial_image_url ?? null])}
      ${links("Customer Invoice", [custDocs?.invoice_url ?? null])}
    </table>
    <p style="color:#64748b;font-size:12px">Generated by MLV Enterprise service automation.</p>
  </div>`;

  const to = process.env.YALE_REPORT_TO || process.env.SMTP_EMAIL;
  if (!isSmtpConfigured() || !to) return;

  await sendMail({
    to,
    subject: `Service Completion — ${lead.yale_ref_no ?? lead.customer_name}`,
    html,
  });

  await supabase
    .from("reports")
    .insert({ job_id: jobId, email_sent: true, email_sent_at: new Date().toISOString() });

  await notifyOwner(
    `📧 Completion report emailed to Yale for ${lead.customer_name} (${lead.yale_ref_no ?? "—"}). Serial: ${job.serial_number ?? "—"}.`
  );
}
